version: "3"
services:
  app:
    build: app
    ports:
      - "80:80"
    links:
      - api
  api:
    build: api
    links:
      - db
    environment:
      DATABASE_URL: "postgres://taketurns:soopersekrit@db/taketurns"
  db:
    image: postgres
    environment:
      POSTGRES_USER: "taketurns"
      POSTGRES_PASSWORD: "soopersekrit"
